export const PRODUCTSLOADING = 'PRODUCTSLOADING';
export const PRODUCTSLISTSUCCESS = 'PRODUCTSLISTSUCCESS';
export const PRODUCTSTFAILED = 'PRODUCTSTFAILED';

export const TOGGLE_SORT_OPTION = 'TOGGLE_SORT_OPTION';


export const ADD_BRAND_OPTION = 'ADD_BRAND_OPTION';
export const REMOVE_BRAND_OPTION = 'REMOVE_BRAND_OPTION';


export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const ADD_TO_FAV = "ADD_TO_FAV";
export const REMOVE_FROM_FAV = "REMOVE_FROM_FAV";

export const ADD_FILTER_MODEL = "ADD_FILTER_MODEL";
export const REMOVE_FILTER_MODEL = "REMOVE_FILTER_MODEL";